const $=s=>document.querySelector(s);
const DEFAULT_AREAS=['Business','Body','Mind','Wellbeing','Personal Growth'];
const dateKey=(d=new Date())=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const uid=()=>crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2);
let entries=[],editId=null,limit=50,ready=false;

const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function accept(data){entries=data.entries;ready=true;$('#connection').textContent='Saved on this device · Add memories whenever you want';$('#connection').classList.remove('error');render()}
function normalize(raw){const array=Array.isArray(raw)?raw:raw?.version===2?raw.entries:null;if(!Array.isArray(array))throw Error('Choose a Compound Your Wins backup.');return array.map(e=>{if(!e||typeof e.title!=='string'||typeof e.date!=='string')throw Error('This backup contains an invalid memory. Nothing was imported.');return {...e,id:e.id||uid(),date:e.date.slice(0,10),category:e.category||'Personal Growth',notes:e.notes||'',chapter:e.chapter||'',highlight:e.highlight===true,archived:e.archived===true}})}
async function load(){
  try{
    accept(await WinsDB.readAll());
  }catch(e){
    $('#connection').textContent='Storage unavailable on this device. Tap here to retry.';
    $('#connection').classList.add('error');
    $('#connection').onclick=load;
    return;
  }
  WinsDB.requestPersistence();
}
function options(select,values,label){const current=select.value;select.replaceChildren(new Option(label,''),...values.map(v=>new Option(v,v)));if(values.includes(current))select.value=current}
function render(){const active=entries.filter(e=>!e.archived);const areas=[...new Set([...DEFAULT_AREAS,...entries.map(e=>e.category)])];options($('#area-filter'),areas,'Every area');options($('#year-filter'),[...new Set(active.map(e=>e.date.slice(0,4)))].sort().reverse(),'Every year');$('#areas').replaceChildren(...areas.map(x=>new Option(x,x)));$('#chapters').replaceChildren(...[...new Set(entries.map(e=>e.chapter).filter(Boolean))].map(x=>new Option(x,x)));$('#score').textContent=active.length;$('#total').textContent=active.length;$('#milestones').textContent=active.filter(e=>e.highlight).length;$('#years').textContent=new Set(active.map(e=>e.date.slice(0,4))).size;chart(active);$('#highlights').replaceChildren();const highlights=active.filter(e=>e.highlight).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,3);if(!highlights.length){$('#highlights').append(el('p','highlight-empty','Your first client. A stronger body. A change in how you think. You decide what mattered.'))}for(const e of highlights){const b=el('button','highlight-card');b.append(el('small','',formatDate(e.date)),el('strong','',e.title));b.onclick=()=>openMemory(e);$('#highlights').append(b)}renderList();renderBusiness();renderGrowth()}
function formatDate(date){return new Date(date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'})}
function renderList(){const q=$('#search').value.toLowerCase().trim(),area=$('#area-filter').value,year=$('#year-filter').value,kind=$('#kind-filter').value;const selected=entries.filter(e=>(kind==='archived'?e.archived:!e.archived)&&(!area||e.category===area)&&(!year||e.date.startsWith(year))&&(kind!=='highlights'||e.highlight)&&(!q||[e.title,e.notes,e.chapter,e.category,e.business?.company].join(' ').toLowerCase().includes(q))).sort((a,b)=>b.date.localeCompare(a.date)||b.id.localeCompare(a.id));$('#entries').replaceChildren();$('#log-count').textContent=` (${selected.length})`;$('#more').hidden=selected.length<=limit;let group='';for(const e of selected.slice(0,limit)){const y=e.date.slice(0,4);if(group!==y){group=y;$('#entries').append(el('h3','year-heading',y))}const b=el('button','memory-row');const side=el('span','memory-date',new Date(e.date+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric'}));const text=el('span','memory-body');const meta=el('span','memory-meta',e.category+(e.chapter?' / '+e.chapter:''));text.append(meta,el('strong','memory-title',e.title));if(e.business||e.growth)text.append(el('span','business-badge',momentLabel(e))); if(e.notes)text.append(el('span','memory-preview',e.notes.length>170?e.notes.slice(0,170)+'…':e.notes));b.append(side,text,el('span','memory-mark',e.highlight?'✳':'↗'));b.onclick=()=>openMemory(e);$('#entries').append(b)}if(!selected.length){const box=el('div','empty');box.append(el('strong','',entries.length?'No memories match this view.':'Start anywhere in your story.'),el('p','',entries.length?'Try another year, area, or search.':'Something from today. Something from ten years ago. It all belongs here.'));$('#entries').append(box)}}
function chart(active){const today=dateKey();let start=active.reduce((d,e)=>e.date<d?e.date:d,today);const p=$('#period').value;if(p==='1')start=today.slice(0,4)+'-01-01';if(p==='10')start=(new Date().getFullYear()-9)+'-01-01';const a=new Date(start+'T12:00:00').getTime(),b=Math.max(a+86400000,new Date(today+'T12:00:00').getTime());const ordered=active.map(e=>e.date).sort();let cursor=0;const samples=Array.from({length:61},(_,i)=>{const t=new Date(a+(b-a)*i/60);const d=dateKey(t);while(cursor<ordered.length&&ordered[cursor]<=d)cursor++;return {date:d,value:cursor}});const max=Math.max(5,active.length);const pts=samples.map((v,i)=>[8+i*684/60,195-v.value/max*170]);const line=pts.map(p=>p.join(',')).join(' ');$('#chart').innerHTML=`<defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#d9ff62" stop-opacity=".18"/><stop offset="1" stop-color="#d9ff62" stop-opacity="0"/></linearGradient></defs>${[25,81,138,195].map(y=>`<line x1="8" y1="${y}" x2="692" y2="${y}" stroke="#333a30" stroke-dasharray="3 6"/>`).join('')}<polygon points="8,205 ${line} 692,205" fill="url(#fill)"/><polyline points="${line}" fill="none" stroke="#d9ff62" stroke-width="3"/><circle cx="692" cy="${pts.at(-1)[1]}" r="5" fill="#d9ff62"/>`;$('#chart').setAttribute('aria-label',`Cumulative memories from ${start} to ${today}: ${active.length} total. Quiet periods stay flat.`);$('#chart-labels').replaceChildren(...[0,20,40,60].map(i=>el('span','',i===60?'Today':new Date(samples[i].date+'T12:00:00').toLocaleDateString('en-US',{month:'short',year:'numeric'}))))}
function openMemory(e){if(!ready){toast('Storage is not ready yet. Try again in a moment.');return}editId=e?.id||null;$('#win-form').reset();$('#form-heading').textContent=e?'A piece of your story.':'What happened?';$('#title').value=e?.title||'';$('#memory-date').max=dateKey();$('#memory-date').value=e?.date||dateKey();$('#category').value=e?.category||'Business';$('#notes').value=e?.notes||'';$('#chapter').value=e?.chapter||'';$('#highlight').checked=e?.highlight||false;$('#archive-entry').hidden=!e;$('#archive-entry').textContent=e?.archived?'Restore to timeline':'Move to archive';$('#save-button').textContent=e?'Save changes':'Keep this memory ↗';fillEvent(e);$('#win-dialog').showModal()}
$('#open-win').onclick=()=>openMemory();$('#close').onclick=()=>$('#win-dialog').close();$('#period').onchange=()=>chart(entries.filter(e=>!e.archived));
$('#win-form').onsubmit=async e=>{e.preventDefault();const button=$('#save-button');button.disabled=true;try{const prev=entries.find(e=>e.id===editId);accept(await WinsDB.saveMemory({id:editId||uid(),title:$('#title').value.trim(),date:$('#memory-date').value,category:$('#category').value.trim(),notes:$('#notes').value,chapter:$('#chapter').value,highlight:$('#highlight').checked,archived:prev?.archived||false,...eventInput()}));$('#win-dialog').close();toast('Saved. Another piece of your story.')}catch(e){toast(e.message)}finally{button.disabled=false}};
$('#archive-entry').onclick=async()=>{const e=entries.find(e=>e.id===editId);if(!e)return;try{accept(await WinsDB.saveMemory({...e,archived:!e.archived}));$('#win-dialog').close();toast(e.archived?'Restored to your timeline.':'Archived. You can restore it anytime.')}catch(e){toast(e.message)}};
for(const id of ['search','area-filter','year-filter','kind-filter'])$('#'+id).addEventListener(id==='search'?'input':'change',()=>{limit=50;renderList()});$('#more').onclick=()=>{limit+=50;renderList()};$('#clear-filters').onclick=()=>{for(const id of ['search','area-filter','year-filter','kind-filter'])$('#'+id).value='';limit=50;renderList()};$('#highlight-filter').onclick=()=>{$('#kind-filter').value='highlights';renderList();$('.log').scrollIntoView({behavior:'smooth'})};
$('#backup-open').onclick=()=>$('#backup-dialog').showModal();$('#backup-close').onclick=()=>$('#backup-dialog').close();function download(data,type,extension){const url=URL.createObjectURL(new Blob([data],{type}));const a=el('a');a.href=url;a.download='compound-your-wins-'+dateKey()+extension;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('#export').onclick=async()=>{try{const data=await WinsDB.readAll();download(JSON.stringify(data,null,2),'application/json','.json');toast('Backup downloaded. Keep it somewhere safe — this device alone is not a backup.')}catch(e){toast(e.message)}};
$('#export-text').onclick=async()=>{try{const data=await WinsDB.readAll();const text=['COMPOUND YOUR WINS — MY LIFE ARCHIVE','Exported '+dateKey(),'',...data.entries.sort((a,b)=>a.date.localeCompare(b.date)).map(e=>`${e.date} | ${e.category}${e.highlight?' | MILESTONE':''}${e.archived?' | ARCHIVED':''}\n${e.title}\n${e.chapter?'Chapter: '+e.chapter+'\n':''}${moveDetail(e,data)}${e.notes||''}\n`)];download(text.join('\n'),'text/plain;charset=utf-8','.txt')}catch(e){toast(e.message)}};
$('#import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>25000000)throw Error('Choose a backup under 25 MB.');const incoming=normalize(JSON.parse(await file.text()));const before=entries.length;const {archive,added}=await WinsDB.importMemories(incoming);accept(archive);toast(`${added} memories added. Existing memories kept.`)}catch(e){toast(e.message)}finally{$('#import').value=''}};
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'log_win',description:'Save a memory to the personal life archive. Omit date to use today.',inputSchema:{type:'object',properties:{title:{type:'string',maxLength:200},category:{type:'string',maxLength:40},date:{type:'string'},notes:{type:'string'},chapter:{type:'string'},highlight:{type:'boolean'}},required:['title','category'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async input=>{const memory={id:uid(),date:dateKey(),notes:'',chapter:'',highlight:false,...input};accept(await WinsDB.saveMemory(memory));return {id:memory.id,saved:true}}})).catch(()=>{})}catch{}}
if('serviceWorker' in navigator){window.addEventListener('load',()=>{navigator.serviceWorker.register('sw.js').catch(()=>{})})}

const KINDS={company:'Company started',income:'Job income',sales:'Sales',investment:'Money invested',reinvestment:'Sales reinvested',practice:'Practice started',shift:'Shift noticed'};
const BUSINESS_KINDS=['company','income','sales','investment','reinvestment'];
const GROWTH_KINDS=['practice','shift'];
let businessLimit=30,growthLimit=30;
const money=(cents,currency)=>new Intl.NumberFormat('en-US',{style:'currency',currency,maximumFractionDigits:cents%100?2:0}).format(cents/100);
function businessLabel(b){return `${KINDS[b.kind]} · ${b.company}${b.amountCents?' · '+money(b.amountCents,b.currency):''}`}
function growthLabel(g){return `${KINDS[g.kind]} · ${g.practice}`}
function momentLabel(e){return e.business?businessLabel(e.business):e.growth?growthLabel(e.growth):''}
function moveDetail(e,data){const m=e.business||e.growth;if(!m)return '';return momentLabel(e)+'\n'+(m.sourceId?'Linked from: '+(data.entries.find(x=>x.id===m.sourceId)?.title||m.sourceId)+'\n':'')}
function toggleEventFields(){const kind=$('#event-kind').value;const isBiz=BUSINESS_KINDS.includes(kind),isGrowth=GROWTH_KINDS.includes(kind);$('#business-fields').hidden=!isBiz;$('#growth-fields').hidden=!isGrowth;$('#company').required=isBiz;$('#amount').required=isBiz&&kind!=='company';$('#amount').min=kind==='company'?'0':'0.01';$('#practice').required=isGrowth}
function fillEvent(e){const b=e?.business,g=e?.growth;$('#event-kind').value=b?.kind||g?.kind||'';$('#company').value=b?.company||'';$('#currency').value=b?.currency||'USD';$('#amount').value=b?.amountCents?String(b.amountCents/100):'';$('#source').replaceChildren(new Option('No linked event yet',''));const bizCandidates=entries.filter(x=>x.id!==e?.id&&x.business).sort((a,c)=>c.date.localeCompare(a.date));for(const x of bizCandidates){$('#source').append(new Option(`${x.date} · ${x.title}${x.archived?' (archived)':''}`,x.id))}if(b?.sourceId)$('#source').value=b.sourceId;$('#practice').value=g?.practice||'';$('#growth-source').replaceChildren(new Option('No linked practice yet',''));const growthCandidates=entries.filter(x=>x.id!==e?.id&&x.growth).sort((a,c)=>c.date.localeCompare(a.date));for(const x of growthCandidates){$('#growth-source').append(new Option(`${x.date} · ${x.title}${x.archived?' (archived)':''}`,x.id))}if(g?.sourceId)$('#growth-source').value=g.sourceId;toggleEventFields()}
function eventInput(){const kind=$('#event-kind').value;if(BUSINESS_KINDS.includes(kind))return {business:{kind,company:$('#company').value.trim(),currency:$('#currency').value,amountCents:Math.round(Number($('#amount').value||0)*100),sourceId:$('#source').value}};if(GROWTH_KINDS.includes(kind))return {growth:{kind,practice:$('#practice').value.trim(),sourceId:$('#growth-source').value}};return {}}
$('#event-kind').onchange=()=>{toggleEventFields();const kind=$('#event-kind').value;if(BUSINESS_KINDS.includes(kind))$('#category').value='Business';else if(GROWTH_KINDS.includes(kind))$('#category').value='Personal Growth'};
$('#add-business').onclick=()=>{openMemory();if(!ready)return;$('#event-kind').value='company';$('#category').value='Business';toggleEventFields()};
$('#add-growth').onclick=()=>{openMemory();if(!ready)return;$('#event-kind').value='practice';$('#category').value='Personal Growth';toggleEventFields()};
$('#company-filter').onchange=()=>{businessLimit=30;renderBusiness()};$('#currency-filter').onchange=()=>{businessLimit=30;renderBusiness()};$('#business-more').onclick=()=>{businessLimit+=30;renderBusiness()};
$('#practice-filter').onchange=()=>{growthLimit=30;renderGrowth()};$('#growth-more').onclick=()=>{growthLimit+=30;renderGrowth()};
function renderBusiness(){const all=entries.filter(e=>e.business&&!e.archived);const companies=[...new Set(all.map(e=>e.business.company))].sort();options($('#company-filter'),companies,'All companies & jobs');$('#companies').replaceChildren(...companies.map(c=>new Option(c,c)));const company=$('#company-filter').value,currency=$('#currency-filter').value;const moves=all.filter(e=>(!company||e.business.company===company)&&e.business.currency===currency).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));const totals=$('#business-totals');totals.replaceChildren();for(const [kind,label] of [['sales','Sales recorded'],['income','Job income recorded'],['investment','Outside money put in'],['reinvestment','Sales money put back in']]){const box=el('div');box.append(el('span','',label),el('strong','',money(moves.filter(e=>e.business.kind===kind).reduce((sum,e)=>sum+e.business.amountCents,0),currency)));totals.append(box)}
const chartBox=$('#business-chart');chartBox.replaceChildren();const sales=moves.filter(e=>e.business.kind==='sales');if(sales.length){const dates=[...new Set(moves.map(e=>e.date))].sort();const first=new Date(dates[0]+'T12:00:00').getTime()-86400000;const last=Math.max(first+86400000,new Date(dates.at(-1)+'T12:00:00').getTime());const total=sales.reduce((n,e)=>n+e.business.amountCents,0);let cumulative=0;const points=[[10,130]];for(const date of dates){const x=10+(new Date(date+'T12:00:00').getTime()-first)/(last-first)*680;points.push([x,130-cumulative/total*110]);cumulative+=sales.filter(e=>e.date===date).reduce((n,e)=>n+e.business.amountCents,0);points.push([x,130-cumulative/total*110])}const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 700 150');svg.setAttribute('role','img');svg.setAttribute('aria-label',`Cumulative recorded sales: ${money(total,currency)}, from ${dates[0]} to ${dates.at(-1)}. This is sales, not profit.`);const line=document.createElementNS(ns,'polyline');line.setAttribute('points',points.map(p=>p.join(',')).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#d9ff62');line.setAttribute('stroke-width','3');svg.append(line);chartBox.append(el('div','flow-label','CUMULATIVE SALES · '+currency),svg,el('p','help',`${formatDate(dates[0])} — ${formatDate(dates.at(-1))} · Sales only. Reinvestment is not counted as new revenue.`))}else chartBox.append(el('p','help','Record a sale to start your sales growth graph. Transfers and reinvestment don’t count as new sales.'));
const flow=$('#business-flow');flow.replaceChildren();$('#business-more').hidden=moves.length<=businessLimit;if(!moves.length){const empty=el('div','empty');empty.append(el('strong','','Show how you got from there to here.'),el('p','','Add your company, a paycheck, a product purchase, or your first sales. Link each move to what made it possible.'));flow.append(empty)}for(const e of moves.slice(-businessLimit)){const row=el('button','business-move');const parent=entries.find(x=>x.id===e.business.sourceId);if(parent)row.append(el('span','source-caption',`From ${parent.title}${parent.archived?' (archived)':''} ↓`));row.append(el('span','memory-meta',formatDate(e.date)+' · '+e.business.company),el('strong','memory-title',e.title),el('span','business-badge',KINDS[e.business.kind]+(e.business.amountCents?' · '+money(e.business.amountCents,currency):'')));if(e.notes)row.append(el('span','memory-preview',e.notes.slice(0,170)));row.onclick=()=>openMemory(e);flow.append(row)}}
function renderGrowth(){const all=entries.filter(e=>e.growth&&!e.archived);const practices=[...new Set(all.map(e=>e.growth.practice))].sort();options($('#practice-filter'),practices,'All practices');$('#practices').replaceChildren(...practices.map(p=>new Option(p,p)));const practice=$('#practice-filter').value;const moves=all.filter(e=>!practice||e.growth.practice===practice).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));const totals=$('#growth-totals');totals.replaceChildren();const practiceCount=moves.filter(e=>e.growth.kind==='practice').length;const shiftCount=moves.filter(e=>e.growth.kind==='shift').length;const linkedShifts=moves.filter(e=>e.growth.kind==='shift'&&e.growth.sourceId).length;for(const [label,value] of [['Practices logged',practiceCount],['Shifts noticed',shiftCount],['Shifts linked to a practice',linkedShifts]]){const box=el('div');box.append(el('span','',label),el('strong','',String(value)));totals.append(box)}
const chartBox=$('#growth-chart');chartBox.replaceChildren();if(moves.length){const dates=[...new Set(moves.map(e=>e.date))].sort();const first=new Date(dates[0]+'T12:00:00').getTime()-86400000;const last=Math.max(first+86400000,new Date(dates.at(-1)+'T12:00:00').getTime());const total=moves.length;let cumulative=0;const points=[[10,130]];for(const date of dates){const x=10+(new Date(date+'T12:00:00').getTime()-first)/(last-first)*680;points.push([x,130-cumulative/total*110]);cumulative+=moves.filter(e=>e.date===date).length;points.push([x,130-cumulative/total*110])}const ns='http://www.w3.org/2000/svg';const svg=document.createElementNS(ns,'svg');svg.setAttribute('viewBox','0 0 700 150');svg.setAttribute('role','img');svg.setAttribute('aria-label',`Cumulative growth entries: ${total} total, from ${dates[0]} to ${dates.at(-1)}.`);const line=document.createElementNS(ns,'polyline');line.setAttribute('points',points.map(p=>p.join(',')).join(' '));line.setAttribute('fill','none');line.setAttribute('stroke','#d9ff62');line.setAttribute('stroke-width','3');svg.append(line);chartBox.append(el('div','flow-label','CUMULATIVE GROWTH ENTRIES'),svg,el('p','help',`${formatDate(dates[0])} — ${formatDate(dates.at(-1))} · Practices, and the shifts you've traced back to them.`))}else chartBox.append(el('p','help','Log a practice or a shift to start tracking your personal growth over time.'));
const flow=$('#growth-flow');flow.replaceChildren();$('#growth-more').hidden=moves.length<=growthLimit;if(!moves.length){const empty=el('div','empty');empty.append(el('strong','','See how your practices shape you.'),el('p','','Log what you practice, and link the shifts you notice back to it.'));flow.append(empty)}for(const e of moves.slice(-growthLimit)){const row=el('button','business-move');const parent=entries.find(x=>x.id===e.growth.sourceId);if(parent)row.append(el('span','source-caption',`From ${parent.title}${parent.archived?' (archived)':''} ↓`));row.append(el('span','memory-meta',formatDate(e.date)+' · '+e.growth.practice),el('strong','memory-title',e.title),el('span','business-badge',KINDS[e.growth.kind]));if(e.notes)row.append(el('span','memory-preview',e.notes.slice(0,170)));row.onclick=()=>openMemory(e);flow.append(row)}}
load();
